amcl:
  ros__parameters:
    
    # Topics
    global_frame_id: "map"
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    scan_topic: scan
    map_topic: map
    
    # Amcl will broadcast tf from map to odom
    tf_broadcast: true 
    transform_tolerance: 1.0
    
    # It restores the robot pose from the last time it was run every .05 seconds.
    save_pose_rate: 0.5
    
    # Initial pose (Guess)
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    
    # Odometry Motion Model
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    
    # Noise of Odometry Motion Model
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
        
    # Laser Motion Model
    laser_model_type: "likelihood_field"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    max_beams: 60
    pf_err: 0.05
    pf_z: 0.99
    sigma_hit: 0.2
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

    # Resampling Algorithm Parameters
    resample_interval: 1
    max_particles: 2000
    min_particles: 500
    
    # Parameters for Localization Recovery
    recovery_alpha_fast: 0.0 # Deactivating
    recovery_alpha_slow: 0.0 # Deactivating

    # In order to trigger an update, the robot must move more than the following values
    update_min_a: 0.2 # Radians
    update_min_d: 0.1 # Meters
 
